### PR TITLE
feat: add icons to the set

### PR DESCRIPTION
**Pull request by kryskirkland**
Resolves [#25027](https://github.com/Arize-ai/arize/issues/25027)

- Adds more icons.

- Revise to alphabetical order for ease of use (adds alphabetical hashes for searchability) 

- Removes `List` to avoid naming conflict. It looks like `ListOutline` and `List`. If approved, will rename `List`  to `ListOutline`

### CODE REVIEW

**Comment by mikeldking** [comment]
> Removes List to avoid naming conflict. It looks like ListOutline and List. If approved, will rename List to ListOutline

Typically not good practice to remove something as it requires a major bump.

**Comment by kryskirkland** [comment]
> > Removes List to avoid naming conflict. It looks like ListOutline and List. If approved, will rename List to ListOutline
> 
> Typically not good practice to remove something as it requires a major bump.

@mikeldking ah - `List` is not originally in this library, only `ListOutline`. So instead of remove, I think omit is a better term

**Comment by mikeldking** [comment]
> > > Removes List to avoid naming conflict. It looks like ListOutline and List. If approved, will rename List to ListOutline
> > 
> > 
> > Typically not good practice to remove something as it requires a major bump.
> 
> @mikeldking ah - `List` is not originally in this library, only `ListOutline`. So instead of remove, I think omit from the migration is a better term. Would the impact still be the same?

Ah I see - yeah better to name outline vs filled. Let's leave as is. Thanks @kryskirkland

**Review by mikeldking — APPROVED** [review]
💅

**Pull request merged**
